update readme with reverse proxy
stardog-union/launchpad-docs pull request #13
Opened 2023-04-25 18:58 UTC by StevePlace68

add instructions on how to secure traffic between the front end and Stardog using a reverse proxy

2023-04-25 20:34 UTC, paulplace commented on README.md
> +To enable communication between the front end (i.e., your browser) and Stardog via HTTPS, you can configure a reverse proxy, such as [nginx](https://nginx.org/en/). Once you have set up your proxy, s
s/and Stardog via HTTPS/and Launchpad via HTTPS/

Also, would be good to provide a simple example config, if possible.

2023-04-25 21:03 UTC, noahgorstein requested changes

2023-04-25 21:03 UTC, noahgorstein commented on README.md
> +To enable communication between the front end (i.e., your browser) and Launchpad via HTTPS, you can configure a reverse proxy, such as [nginx](https://nginx.org/en/). Once you have set up your proxy,
```suggestion
To enable HTTPS communications for Launchpad, you can configure a reverse proxy or load balancer, such as [nginx](https://nginx.org/en/). Once you have set up your proxy/load balancer, set the `BASE_URL` environment variable to its address. 
```

Any time you need to change the config for Launchpad, a restart is required. This is not specific to this setting. 
Maybe mention here a link to securing communications between Stardog and Launchpad because that is not what is being described in this section but I could see someone looking for that info next or wondering "okay now the Launchpad application can be visited via HTTPS but how can I make sure that the traffic between Launchpad and my Stardog server is also encrypted via HTTPS ...".

2023-04-25 21:30 UTC, paulplace commented on README.md
> +
Okay, this is my fault, as I asked for a sample config. Maybe just omit the sample nginx config?

2023-04-25 21:33 UTC, paulplace commented on README.md
> +
Apologies to @StevePlace68 for all the churn on this.

2023-04-25 21:35 UTC, StevePlace68 commented on README.md
> +
No worries

2023-04-26 15:11 UTC, noahgorstein requested changes

2023-04-26 15:11 UTC, noahgorstein commented on README.md
> +To secure communications between Stardog and Launchpad, see [SSL Cert Verification](./README.md#ssl-cert-verification).
```suggestion
To secure communications between Stardog and Launchpad, see [SSL Cert Verification](#ssl-cert-verification).
```

This will make it such that Github won't reload the page when clicking on the hyperlink. It'll just move up/down the document already loaded.

2023-04-26 15:37 UTC, merged