[CLOUD-1352] Adding doc for Launchpad's Azure access token passthrough mode
stardog-union/launchpad-docs pull request #16
Opened 2023-09-04 22:53 UTC by paulplace

2023-09-15 20:17 UTC, PaulJackson123 requested changes
Very nice. Will be helpful to me the next time I need to set this up.

I made a couple comments around how the access key isn't sent from Stardog to the data source directly, rather it's exchanged through the on-behalf-of flow.

It took me a bit to understand what was meant by "passthrough". In this context it means the access token that is obtains by launchpad from Azure AD is used to authenticate with Stardog. I was confused because we also use that term for VG passthrough. Not necessarily requesting a change.

2023-09-15 20:17 UTC, PaulJackson123 commented on azure/access-token-passthrough-mode.md
> +Here are steps to create and register Launchpad as a Microsoft Application. Note that these are almost identical to the steps in the [basic mode example](./README.md#how-to-register-the-application),
Should you indicate here that you'll be registering Launchpad as a web application, in the same way that you indicated that Stardog would be registered as a Mobile and desktop application?

2023-09-19 17:48 UTC, paulplace commented on README.md
> +| -------------------------------------- | -------------------- | ----------------------------------------- | -----------------------------------------------------------------------------------------
I don't _think_ so. I played with the formatting a bit, but I couldn't really get the markdown table formatter to do things differently.

2023-09-19 17:49 UTC, paulplace commented on azure/README.md
> +  Note over Launchpad,Stardog: Launchpad generates a JWT that the Stardog server is <br> configured to accept, using information from Azure's JWT.
I will re-word.

2023-09-19 17:53 UTC, paulplace commented on azure/access-token-passthrough-mode.md
> +This example builds on the [basic mode example](./README.md), adding support for access token passthrough mode, wherein Launchpad requests an identity token from Azure AD for the purpose of authentic
Thank you for the clarifying verbiage. I will use it.

2023-09-19 18:03 UTC, paulplace commented on azure/access-token-passthrough-mode.md
> +In **access token passthrough mode**, Launchpad requests both an identity token and an access token from Azure AD for an authenticated user. Launchpad uses the identity token to verify that the user
I added your more detailed explanation above, so I will leave this as-is.

2023-09-21 19:18 UTC, merged